### ISSUE TITLE
Build error: Type '(BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | BaseWebhookEvent<"meta"> | ... 199 more ... | (BaseWebhookEvent<...> & { ...; })) & { ...; }' does not satisfy the constraint 'Options<unknown>'.

### ISSUE THREAD

**Issue by gr2m** [octokit/app.js#212] opened 2021-03-08 18:39 UTC
This is a follow up to https://github.com/octokit/app.js/pull/201 @G-Rath @oscard0m @wolfy1339 

I get the following error since yesterdays lock file update which bumped `@octokit/webhooks` from 8.4.1 to 8.5.3 and `@octokit/webhooks-definitions` to 3.61.0 to 3.62.5

Any idea what it could be?

```
error TS2344: Type '(BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | BaseWebhookEvent<"meta"> | ... 199 more ... | (BaseWebhookEvent<...> & { ...; })) & { ...; }' does not satisfy the constraint 'Options<unknown>'.
  Type 'BaseWebhookEvent<"push"> & { octokit: Octokit; }' has no properties in common with type 'Options<unknown>'.

13 ): Webhooks<EmitterWebhookEvent & { octokit: Octokit }> {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/webhooks.ts:14:3 - error TS2322: Type 'Webhooks<{ secret: string; path: string; transform: (event: BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | ... 200 more ... | (BaseWebhookEvent<...> & { ...; })) => Promise<...>; }>' is not assignable to type 'Webhooks<(BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | BaseWebhookEvent<"meta"> | ... 199 more ... | (BaseWebhookEvent<...> & { ...; })) & { ...; }>'.
  Type '{ secret: string; path: string; transform: (event: BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | ... 200 more ... | (BaseWebhookEvent<...> & { ...; })) => Promise<...>; }' is not assignable to type '(BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | BaseWebhookEvent<"meta"> | ... 199 more ... | (BaseWebhookEvent<...> & { ...; })) & { ...; }'.
    Type '{ secret: string; path: string; transform: (event: BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | ... 200 more ... | (BaseWebhookEvent<...> & { ...; })) => Promise<...>; }' is not assignable to type 'BaseWebhookEvent<"workflow_run"> & { payload: { action: "requested"; }; } & { octokit: Octokit; }'.
      Type '{ secret: string; path: string; transform: (event: BaseWebhookEvent<"push"> | BaseWebhookEvent<"public"> | BaseWebhookEvent<"label"> | ... 200 more ... | (BaseWebhookEvent<...> & { ...; })) => Promise<...>; }' is missing the following properties from type 'BaseWebhookEvent<"workflow_run">': id, name, payload

 14   return new Webhooks({
      ~~~~~~~~~~~~~~~~~~~~~
 15     secret: options.secret,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 57     },
    ~~~~~~
 58   });
    ~~~~~
```

**Comment by wolfy1339** [comment] 2021-03-10 01:15
Looking at the changes from https://github.com/octokit/webhooks/compare/v3.61.0...v3.62.5 I don't see anything that would cause issues upstream.

However, when i check the changes from https://github.com/octokit/webhooks.js/compare/v8.4.1...v8.5.3 I do see some refactoring that happened around the type parameters for the `Webhooks` class, which seems to line up with the build error

**Comment by wolfy1339** [comment] 2021-03-10 01:37
I believe this diff should do the trick, no errors are reported at build time when I use it:
```diff
diff --git a/src/webhooks.ts b/src/webhooks.ts
index 698ebb3..d03473b 100644
--- a/src/webhooks.ts
+++ b/src/webhooks.ts
@@ -10,11 +10,17 @@ export function webhooks(
   options: Required<Options>["webhooks"]
   // Explict return type for better debugability and performance,
   // see https://github.com/octokit/app.js/pull/201
-): Webhooks<EmitterWebhookEvent & { octokit: Octokit }> {
+): Webhooks<
+  Required<Options>["webhooks"] & {
+    transform: (
+      event: EmitterWebhookEvent
+    ) => Promise<EmitterWebhookEvent & { octokit: Octokit }>;
+  }
+> {
   return new Webhooks({
     secret: options.secret,
     path: "/api/github/webhooks",
-    transform: async (event) => {
+    transform: async (event: EmitterWebhookEvent) => {
       if (
         !("installation" in event.payload) ||
         typeof event.payload.installation !== "object"
```

**Comment by oscard0m** [comment] 2021-03-12 21:49
Issue is happening in this branch: `renovate/lock-file-maintenance`
Check Run where the issue is happening: https://github.com/octokit/app.js/pull/211/checks?check_run_id=2079497901

**Comment by wolfy1339** [comment] 2021-03-14 20:21
Fixed by octokit/webhooks.js#494

**Closed** 2021-03-15 08:03 UTC
Labels: maintenance, typescript
